### ISSUE TITLE
Inquiry About Performance on the miniF2F Test Set

### ISSUE THREAD

**Issue by tangzhy** [InternLM/InternLM-Math#1]
Hi,

I am reaching out to express my admiration for your exceptional work in the field of mathematical reasoning. The comprehensive use of data and tasks with Lean in your research has truly set a benchmark in this domain.

Given the breadth of your expertise, I am curious to learn about your experiences with the miniF2F test set. Specifically, I am interested in understanding how your model performs on this set. Any insights or results you could share would be highly valuable.

Additionally, if you have any observations or thoughts on the approach to Formal Proof search, I would be extremely eager to hear them.

Thank you for your time and for the impactful work you continue to do. I look forward to potentially learning from your experiences.

**Comment by yinghy18** [comment]
We are still summarizing results on formal reasoning, will provide performance when we give tech report.

**Comment by yinghy18** [comment]
<img width="520" alt="image" src="https://github.com/InternLM/InternLM-Math/assets/56391069/9e15df0d-398d-44a9-acb9-e8698cccf14f">
