### ISSUE TITLE
Performance on Minif2f-valid

### ISSUE THREAD

**Issue by heyubox** [InternLM/InternLM-Math#11]
Thank you for your valuable contribution to formal theorem proving. I would like to cite your work but I didn't find a reported result on the pass rate of minif2f-valid. I am sorry I don't have enough resources now to reproduce the results. So I wonder if you have done any evaluation on minif2f-valid. What is the performance? Thank you in advance!

**Comment by objecti0n** [comment]
internlm2-base-math-7b 29.9% and internlm2-base-math-20b 31.6%

**Comment by heyubox** [comment]
Thanks for your reply!
