### ISSUE TITLE
Kindly ask about the size of lean-workbook

### ISSUE THREAD

**Issue by freyaya123** [InternLM/InternLM-Math#41]
Hi authors, 
You mentioned that '''Our dataset contains 57231 problems in the split of Lean Workbook and 82893 problems in the split of Lean Workbook Plus. We provide the natural language statement, answer, formal statement, and formal proof (if available) for each problem. These data can support autoformalization model training and searching for proofs.'''. Unfortunately, I only saw 25.2k data at the huggingface dataset card. So I wonder why and is that all of the data you used in your paper? 
<img width="854" alt="image" src="https://github.com/user-attachments/assets/b79af6fe-9fc6-4354-8901-4f8ca63b4476">
Thank you!

**Comment by freyaya123** [comment]
> 25.2K data is the proof and disprove we found in Lean-workbook-plus. The original problem set is here **https://huggingface.co/datasets/internlm/Lean-Workbook/blob/main/lean_workbook.json**. Sorry for confusion.

Yes I'll also see this one. But I found that most of these data has an empty proof of proof with ''sorry''. So could you please clarify the whole training data you used? Such as, how much data with formal proof, and how much with only formal statement?

**Comment by objecti0n** [comment]
``sorry`` means we haven't found its proof. I don't know if you are asking for training translator or prover? Prover only use data with formal proof, training translator use with formal statements.
