### ISSUE TITLE
About critic-guide search in InternLM2.5-StepProver

### ISSUE THREAD

**Issue by LuoKaiGSW** [InternLM/InternLM-Math#42]
Thank you for your work on InternLM2.5-StepProver. I have two questions:
1. The difference between critic-guide search and BFS lies in using the critic model's score to guide the search process. However, this model uses state information as input, so if the sampling number is 32, each step needs to interact with the Lean compiler up to 32 times, which is a significant time cost. In contrast, BFS only needs to interact with Lean once per step. Is this understanding correct?
2. For BFS, if an error occurs at a certain step, the search will terminate. But for critic-guide search, to obtain the critic model score, the prerequisite is that the compilation succeeds to get the state information. Therefore, the tactics that result in errors will be discarded. This setup seems somewhat unfair, doesn't it?

**Comment by wzj423** [comment]
1. The sampling number is 32 for both Best-First and Critic-Guide. This represents the number of tactic candidates generated (they are "candidates" since they might not work), each of which is then passed to the Lean REPL to obtain the next Lean state. BF then ranks these states by averaging log probability scores, while CG passes these Lean states to the critique model for scoring. Thus, there is no difference in how they interact with Lean. 

2. It depends. Since Lean has a C++ kernel, any exceptions thrown by C++ will instantly terminate the Lean process, regardless of CG/BF. Exceptions thrown by Lean itself indicate that certain tactic candidates cannot work. Such candidates will be discarded, of course. Again, the process is essentially the same for CG and BF.

**Comment by bhwangfy** [comment]
Following the question, may I ask what is the template of the prompt for the critic model? I wrote a version according to what the paper mentions, but not sure if it is proper:
```
prompt = "Which state is closer to 'no goals'?"
answer1 = "no goals"
chat = [
        {"role": "user", "content": prompt},
        {"role": "assistant", "content": answer1},
    ]
critic_model.get_score(tokenizer, chat)
```

**Comment by LuoKaiGSW** [comment]
> "role": "user", "content": prompt},
>         {"role": "assistant"

Thank you for your reply. I have tried the two points mentioned in the paper:
1. Using your open-source critic model to score and guide BFS, which indeed achieved positive results on minif2f.
2. Adding the previous proof to the prompt and deleting some data that seemed problematic to me, but this actually led to a performance decline. Of course, it is possible that I mistakenly deleted some data, so I would like to ask about the following example of the rot_add_assoc theorem. It appears to be proved at step id=2, showing no_goals, so I discarded steps id=3-7. Is this the correct approach?
![Uploading DX-20241028@2x.png…]()

**Comment by LuoKaiGSW** [comment]
> 1. The sampling number is 32 for both Best-First and Critic-Guide. This represents the number of tactic candidates generated (they are "candidates" since they might not work), each of which is then passed to the Lean REPL to obtain the next Lean state. BF then ranks these states by averaging log probability scores, while CG passes these Lean states to the critique model for scoring. Thus, there is no difference in how they interact with Lean.
> 2. It depends. Since Lean has a C++ kernel, any exceptions thrown by C++ will instantly terminate the Lean process, regardless of CG/BF. Exceptions thrown by Lean itself indicate that certain tactic candidates cannot work. Such candidates will be discarded, of course. Again, the process is essentially the same for CG and BF.

Thank you for your reply. I have tried the two points mentioned in the paper:
1. Using your open-source critic model to score and guide BFS, which indeed achieved positive results on minif2f.
2. Adding the previous proof to the prompt and deleting some data that seemed problematic to me, but this actually led to a performance decline. Of course, it is possible that I mistakenly deleted some data, so I would like to ask about the following example of the rot_add_assoc theorem. It appears to be proved at step id=2, showing no_goals, so I discarded steps id=3-7. Is this the correct approach?
<img width="1401" alt="DX-20241028@2x" src="https://github.com/user-attachments/assets/b2344fe4-ab21-446c-91f0-746900a56ace">

**Comment by LuoKaiGSW** [comment]
> Following the question, may I ask what is the template of the prompt for the critic model? I wrote a version according to what the paper mentions, but not sure if it is proper:
> 
> ```
> prompt = "Which state is closer to 'no goals'?"
> answer1 = "no goals"
> chat = [
>         {"role": "user", "content": prompt},
>         {"role": "assistant", "content": answer1},
>     ]
> critic_model.get_score(tokenizer, chat)
> ```

Yes, I think it is right.

**Comment by wzj423** [comment]
> > 1. The sampling number is 32 for both Best-First and Critic-Guide. This represents the number of tactic candidates generated (they are "candidates" since they might not work), each of which is then passed to the Lean REPL to obtain the next Lean state. BF then ranks these states by averaging log probability scores, while CG passes these Lean states to the critique model for scoring. Thus, there is no difference in how they interact with Lean.
> > 2. It depends. Since Lean has a C++ kernel, any exceptions thrown by C++ will instantly terminate the Lean process, regardless of CG/BF. Exceptions thrown by Lean itself indicate that certain tactic candidates cannot work. Such candidates will be discarded, of course. Again, the process is essentially the same for CG and BF.
> 
> Thank you for your reply. I have tried the two points mentioned in the paper:
> 
> 1. Using your open-source critic model to score and guide BFS, which indeed achieved positive results on minif2f.
> 2. Adding the previous proof to the prompt and deleting some data that seemed problematic to me, but this actually led to a performance decline. Of course, it is possible that I mistakenly deleted some data, so I would like to ask about the following example of the rot_add_assoc theorem. It appears to be proved at step id=2, showing no_goals, so I discarded steps id=3-7. Is this the correct approach?
> 
> <img alt="DX-20241028@2x" width="1401" src="https://private-user-images.githubusercontent.com/49229809/380610540-b2344fe4-ab21-446c-91f0-746900a56ace.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAxNjU0OTcsIm5iZiI6MTczMDE2NTE5NywicGF0aCI6Ii80OTIyOTgwOS8zODA2MTA1NDAtYjIzNDRmZTQtYWIyMS00NDZjLTkxZjAtNzQ2OTAwYTU2YWNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI5VDAxMjYzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg0MmE3MjkwMTc2YTZjNmVkNjUwMzRmZGE4ZGEyYWFmNmU0MDU4M2UyMWQ3ZTVlZGY0NTY4OTczY2M0OThmNmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.zncKGRqY-MbIVMqHwoJKEDp2W6r2FffjkKymdYey-8c">

The search algorithm stops immediately when "no goals" is met. Regarding the previous proof issue, here are some related discussions: [Lean Zulip Chat](https://leanprover.zulipchat.com/#narrow/channel/219941-Machine-Learning-for-Theorem-Proving/topic/InternLM2.2E5-StepProver/near/478613668). It is designed to alleviate the "swinging back and forth" issue. However, we haven't conducted experiments on other base models, so whether this phenomenon is model/approach-agnostic is still unknown.

**Comment by LuoKaiGSW** [comment]
> > > 1. The sampling number is 32 for both Best-First and Critic-Guide. This represents the number of tactic candidates generated (they are "candidates" since they might not work), each of which is then passed to the Lean REPL to obtain the next Lean state. BF then ranks these states by averaging log probability scores, while CG passes these Lean states to the critique model for scoring. Thus, there is no difference in how they interact with Lean.
> > > 2. It depends. Since Lean has a C++ kernel, any exceptions thrown by C++ will instantly terminate the Lean process, regardless of CG/BF. Exceptions thrown by Lean itself indicate that certain tactic candidates cannot work. Such candidates will be discarded, of course. Again, the process is essentially the same for CG and BF.
> > 
> > 
> > Thank you for your reply. I have tried the two points mentioned in the paper:
> > 
> > 1. Using your open-source critic model to score and guide BFS, which indeed achieved positive results on minif2f.
> > 2. Adding the previous proof to the prompt and deleting some data that seemed problematic to me, but this actually led to a performance decline. Of course, it is possible that I mistakenly deleted some data, so I would like to ask about the following example of the rot_add_assoc theorem. It appears to be proved at step id=2, showing no_goals, so I discarded steps id=3-7. Is this the correct approach?
> > 
> > <img alt="DX-20241028@2x" width="1401" src="https://private-user-images.githubusercontent.com/49229809/380610540-b2344fe4-ab21-446c-91f0-746900a56ace.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAxNjU0OTcsIm5iZiI6MTczMDE2NTE5NywicGF0aCI6Ii80OTIyOTgwOS8zODA2MTA1NDAtYjIzNDRmZTQtYWIyMS00NDZjLTkxZjAtNzQ2OTAwYTU2YWNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI5VDAxMjYzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg0MmE3MjkwMTc2YTZjNmVkNjUwMzRmZGE4ZGEyYWFmNmU0MDU4M2UyMWQ3ZTVlZGY0NTY4OTczY2M0OThmNmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.zncKGRqY-MbIVMqHwoJKEDp2W6r2FffjkKymdYey-8c">
> 
> The search algorithm stops immediately when "no goals" is met. Regarding the previous proof issue, here are some related discussions: [Lean Zulip Chat](https://leanprover.zulipchat.com/#narrow/channel/219941-Machine-Learning-for-Theorem-Proving/topic/InternLM2.2E5-StepProver/near/478613668). It is designed to alleviate the "swinging back and forth" issue. However, we haven't conducted experiments on other base models, so whether this phenomenon is model/approach-agnostic is still unknown.

Thank you for your reply. I will conduct more experiments to verify this conclusion.
